### PR TITLE
go v1.13.4

### PR DESCRIPTION
**Pull request by chenrui333**
[aliyun-cli formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aliyun-cli.rb) is already built with go v1.13.4, so adding it to here.

### CODE REVIEW

**Comment by night556** [comment]
> [aliyun-cli formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aliyun-cli.rb) is already built with go v1.13.4, so adding it to here.

Thank you for your contribution. Since version 1.13 will cause problems in the makefile, we have not added the version 1.13 test. But we will change the makefile as soon as possible.

**Comment by chenrui333** [comment]
@night556 that is good to know. Not quite sure why the Makefile has some issue, happy to take a peek on it. :)

**Comment by night556** [comment]
> @night556 that is good to know. Not quite sure why the Makefile has some issue, happy to take a peek on it. :)

`go get -u github.com / aliyun / aliyun-openapi-meta` is used in the makefile to obtain the aliyun-openapi-meta file, but under the go module mechanism, the obtained file is not in the defined GOPATH, which causes` go- bindata -o resource / metas.go -pkg resource -prefix ../aliyun-openapi-meta ../ aliyun-openapi-meta / ... `statement error

**Comment by JacksonTian** [comment]
Add new version into test is OK. the vendor update should not commit directly or use another pull request.

**Pull request closed without merging**
